### ISSUE TITLE
Membership check for joint Foundations and Standards team council

### ISSUE THREAD

**Issue by ivanov** [jupyter/foundations-and-standards-team-compass#1]
Per https://github.com/jupyter/governance/issues/196 - I've gone ahead and created a joint team compass for Foundations and Standards subproject.

I initially populated the membership from the union of the two previous groups, but wanted to trigger a [membership maintenance check](https://jupyter-foundations-and-standards.readthedocs.io/en/latest/team/becoming-member.html#membership-maintenance)

> Every six months, one currently active member should open an issue in the team-compass repo asking all currently active team members to reply if they still consider themselves active. If not (or no response is given by a team member), it will be assumed that they have gone inactive. This will help keep the active member list up-to-date.
> 
> Remember, an inactive member can return at any time by simply changing their status on the team-compass page.

Please indicate below one way or the other if you would like to remain as an active member of this council, or if you prefer to become inactive at this time.

This poll will remain open until the **first week of January, 2024**, at which point we will assume an `inactive` role for anyone not participating. 

Also, you can leave a comment here if your affiliation is not correct, I did my best (which is never good enough) ;)

- @damianavila wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @kevin-bates wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @Carreau wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @SylvainCorlay wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @jasongrout wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @ivanov wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @rgbkrk wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @minrk wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @JohanMabille wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @mseal wishes to …
    - [ ] remain `active`
    - [ ] become `inactive`

- @blink1073 wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

- @willingc wishes to …
    - [x] remain `active`
    - [ ] become `inactive`

**Comment by ivanov** [comment]
created a @jupyter/foundations-and-standards-council list for us, too.

**Comment by jasongrout** [comment]
Thanks for doing this, @ivanov!

**Comment by JohanMabille** [comment]
Thanks @ivanov ! It seems that I don't have the right to edit the initial post, so I cannot check the box. I wish to remain active for the next year.

**Comment by willingc** [comment]
Thanks @ivanov 🥇

**Comment by ivanov** [comment]
apologies, @JohanMabille - I made a team for us but neglected to give that team admin rights to this repo. Should be fixed  now, though I think Matthias (or perhaps someone else) already checked the box on your behalf.

**Comment by rgbkrk** [comment]
Thanks for kicking this off @ivanov!

**Comment by ivanov** [comment]
With the first week of January 2024 now behind us (happy new year!) , in #2 I have updated the roster based on the results of this membership check.
