### ISSUE TITLE
election of Software Steering Council representative

### ISSUE THREAD

**Issue by ivanov** [jupyter/foundations-and-standards-team-compass#3]
Dear @jupyter/foundations-and-standards-council ,

I've been serving as the Jupyter Subproject Steering Council (SSC) for this subproject, and I am happy to continue to do so. In the team compass documentation we have, which I adapted from [this template](https://github.com/jupyter/team-compass-template) , I included a section reflecting the current representative that I copied from the JupyterLab, which reads

> Each official subproject in Jupyter gets a single Software Steering Council Representative. JupyterLab’s representative is elected by the members. This representative should be re-elected every year (i.e. in January).

I don't think we ever discussed as a subproject how frequently or when we should re-elect the SSC representative, but it seems like a reasonable course of action, and it also happens to be January.

Per [Project Jupyter Software Steering Council section on term length](https://jupyter.org/governance/software_steering_council.html#term-length), we are advised that

> There is no term length for SSC membership, as each Jupyter Subproject is in charge of selecting its own representative. Projects are encouraged to define their own expectations around SSC membership tenure, to share SSC membership responsibilities among core team members, and to provide mechanisms for healthy rotation that avoid burnout.

Having said all that, I'd like to open up this thread for other nominations for SSC representative for this subproject (self nominations are acceptable, I just did it). I propose we hold the nomination period open for two weeks until January 22nd, and then use the two weeks following that (Jan 22-Feb 5) for the election.

Update: Jan 28th

We are a week behind on starting this election. No one else has stepped forward with a nomination so we are running the election with one candidate.

Please indicate your choice by February 12th.

- @damianavila votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @kevin-bates votes for…
    - [ ] Paul Ivanov
    - [ ] none of the above

- @Carreau votes for…
    - [ ] Paul Ivanov
    - [ ] none of the above

- @SylvainCorlay votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @jasongrout votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @ivanov votes for…
    - [ ] Paul Ivanov
    - [x] none of the above

- @rgbkrk votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @minrk votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @JohanMabille votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @blink1073 votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

- @willingc votes for…
    - [x] Paul Ivanov
    - [ ] none of the above

**Comment by ivanov** [comment]
I'm running a week behind on running the election, but no one has stepped forward with a nomination to be this subproject's software steering council representative. As a result, I am opening this up with myself or "None of the above" as the candidates, and sending an email to the foundations and standards council list with a reminder to vote here.

**Comment by rgbkrk** [comment]
Thank you Paul!

**Comment by ivanov** [comment]
Coming back late to this, With 8 votes for "Paul Ivanov", 1 for "none of the above" and 2 non-votes, we have quorum. Thanks everyone!
